# Generated by Django 3.1.4 on 2020-12-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_published',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='is_published',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
