# Generated by Django 3.1.4 on 2020-12-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201221_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.CharField(choices=[('ExternalLink', 'Link outside our domain (ex: google.com/milk)'), ('InternalLink', 'Link inside our domain (ex: /contact)')], default='InternalLink', max_length=20),
        ),
    ]
