# Generated by Django 3.1.4 on 2020-12-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0002_auto_20201220_2006'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='WantToHelp',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=225)),
                        ('email', models.EmailField(max_length=255)),
                        ('description', models.TextField()),
                    ],
                    options={
                        'verbose_name': 'want to help',
                        'verbose_name_plural': 'want to help',
                        'db_table': 'want_to_help',
                    },
                ),
            ],
            database_operations=[]
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='opportunity_categories',
            new_name='categories',
        ),
    ]
