# Generated by Django 3.1.4 on 2020-12-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_auto_20201221_1455"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="link",
            field=models.CharField(max_length=1000),
        ),
    ]
