# Generated by Django 3.1.4 on 2020-12-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_auto_20201221_1518"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.TextField(blank=True, default="", max_length=250),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("TEXT", "Text"), ("IMAGE", "Image")],
                        default="TEXT",
                        max_length=5,
                    ),
                ),
                ("value", models.TextField(max_length=300)),
                ("image", models.ImageField(blank=True, default=None, upload_to="")),
            ],
            options={
                "db_table": "settings",
            },
        ),
    ]
