# Generated by Django 3.1.4 on 2020-12-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
