# Generated by Django 3.1.4 on 2020-12-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunitycategory',
            options={'verbose_name': 'opportunity category', 'verbose_name_plural': 'opportunity categories'},
        ),
        migrations.AlterModelOptions(
            name='wanttohelp',
            options={'verbose_name': 'want to help', 'verbose_name_plural': 'want to help'},
        ),
        migrations.RemoveField(
            model_name='opportunitycategory',
            name='id',
        ),
        migrations.AlterField(
            model_name='opportunitycategory',
            name='slug',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='opportunitycategory',
            table='opportunity_categories',
        ),
    ]
