# Generated by Django 3.1.5 on 2021-01-26 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="updated",
        ),
        migrations.RemoveField(
            model_name="opportunity",
            name="updated",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="updated",
        ),
        migrations.AddField(
            model_name="category",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name="created"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name="modified"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="opportunities",
            field=models.ManyToManyField(
                blank=True,
                related_name="categories",
                related_query_name="category",
                to="administration.Opportunity",
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opportunities",
                related_query_name="opportunity",
                to="administration.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="organisation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profiles",
                related_query_name="profile",
                to="administration.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                related_query_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
