# Generated by Django 3.1.6 on 2021-02-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_email_confirmed",
            field=models.BooleanField(default=False, verbose_name="email confirmed"),
        ),
    ]
