# Generated by Django 3.1.4 on 2020-12-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitycategory',
            name='opportunities',
            field=models.ManyToManyField(blank=True, to='administration.Opportunity'),
        ),
    ]
