# Generated by Django 3.1.5 on 2021-01-30 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20210126_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=225, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='opportunities',
            field=models.ManyToManyField(blank=True, related_name='categories', related_query_name='category', to='administration.Opportunity', verbose_name='opportunities'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='deadline',
            field=models.DateTimeField(verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.TextField(max_length=300, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', related_query_name='opportunity', to='administration.organisation', verbose_name='organisation'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='url',
            field=models.URLField(blank=True, default=None, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='description',
            field=models.TextField(blank=True, max_length=300, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='location',
            field=models.CharField(blank=True, max_length=40, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='website',
            field=models.URLField(blank=True, default=None, verbose_name='website'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(max_length=300, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', related_query_name='profile', to='administration.organisation', verbose_name='organisation'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', related_query_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
