# Generated by Django 3.1.4 on 2020-12-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_examplemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
