# Generated by Django 3.1.4 on 2020-12-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20201220_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='opportunitycategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='is_published',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
