# Generated by Django 3.1.6 on 2021-05-03 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20210206_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='location',
            field=models.CharField(default='', max_length=300, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='roles',
            field=models.CharField(default='', max_length=500, verbose_name='roles'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='schedule',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='schedule'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='name',
            field=models.CharField(max_length=300, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='organisation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', related_query_name='opportunity', to='administration.organisation', verbose_name='organisation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='url',
            field=models.URLField(blank=True, default='', verbose_name='url'),
        ),
    ]
