# Generated by Django 3.1.4 on 2020-12-20 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201220_2006'),
        ('administration', '0003_auto_20201220_2006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpportunityCategory',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
    ]
