# Generated by Django 3.1.6 on 2021-05-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20210503_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='schedule',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='schedule'),
        ),
    ]
