# Generated by Django 3.1.4 on 2020-12-20 20:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('administration', '0004_auto_20201220_2203'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='WantToHelp',
                ),
            ], database_operations=[])
    ]
