# Generated by Django 3.1.4 on 2020-12-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField()),
                ('link', models.URLField()),
                ('image', models.ImageField(blank=True, default=None, upload_to='')),
                ('parent', models.CharField(blank=True, default=None, max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
