# Generated by Django 3.1.4 on 2020-12-18 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_news'),
        ('administration', '0005_auto_20201218_1906'),
    ]

    operations = [
    ]
