# Generated by Django 3.1.4 on 2020-12-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_delete_wanttohelp'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
            preserve_default=False,
        ),
    ]
