# Generated by Django 3.1.4 on 2020-12-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20201212_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='bla',
            field=models.CharField(blank=True, max_length=21),
        ),
    ]
