# Generated by Django 3.1.4 on 2020-12-19 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_opportunity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'verbose_name': 'opportunity', 'verbose_name_plural': 'opportunities'},
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.organization'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='slug',
            field=models.SlugField(),
        ),
    ]
