# Generated by Django 3.1.4 on 2020-12-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_auto_20201219_1620'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organization',
            new_name='Organisation',
        ),
    ]
