# Generated by Django 3.1.4 on 2020-12-19 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_auto_20201219_1640'),
        ('administration', '0005_auto_20201216_1308'),
    ]

    operations = [
    ]
